version: '3.8'

services:
  csvserver:
    build: .
    ports:
      - "9393:9300"
    env_file:
      - csvserver.env
  prometheus:
    image: prom/prometheus:v2.45.2
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"